### PR TITLE
Remove auth_shadow_umask variable.

### PR DESCRIPTION
**Pull request by bfabio**
The auth_shadown_umask variable set the umask for a lot more cases than
just the home directories. You can now set the umask for home directories
with the debops.users role.

### CODE REVIEW

**Comment by bfabio** [comment]
I think the `auth_pam_mkhomedir_umask` variable should be dealt with as well.

Can we have a variable shared across roles (fe `debops__homedir_umask`)? That way we could leave the`pam_mkhomedir.so` stuff in `debops.auth`.

**Comment by drybjed** [comment]
For this variable to be effective, you would want to include the role that defines it in all the playbooks that use that variable. The better way to deal with this would be to define an Ansible local fact that defines the umask; then all other roles that need that value can access it.

I suppose that the current best place to configure it would be in the `debops.core` role - you can define `core__homedir_umask` variable there and define it on the hosts as the `ansible_local.core.homedir_umask` fact. Then other roles like `debops.ath` can get the value from that fact, and if it doesn't exist, provide a sane default.

**Comment by muelli** [comment]
Why do you remove this functionality rather than updating the documentation?
The reasoning for removing seems a bit sparse.

> The  auth_shadown_umask variable set the umask for a lot more cases than just the home directories

yeah. It's the system wide default umask rather than a default home directory umask as was written in the documentation.  I want to change that default umask to prevent world readable files by default.  I don't know any other way of achieving that.

**Comment by drybjed** [comment]
The reason for me to remove this variable and task from the `debops.auth` role was, apart from changing the default system-wide umask via `pam_umask`, the fact that Ansible modified the original `/etc/login.defs` configuration file which could mess up the upgrade process of the `login` package which owns that file. I think that creating a separate `debops.login` role to configure this file properly with diverted original copy might be a better approach. The role doesn't need to configure all available options at the start, just some more interesting ones.

The removed variable set the umask to `0027` by default which could mess with other things if not accounted for, for example support for ACME CA suffered because of it - the challenge response files created by the `acme-tiny` script were unreadable by the webserver. Therefore I think that using more specific umask when needed instead of system-wide is a better approach.

In the new role I would stick to `022` default but let the administrators change it as needed.

**Pull request merged**
