### PR TITLE
Update apt cache before installing required packages

### PR DESCRIPTION
**Pull request by antoineco**
Prevents errors like `package 'libpam-cracklib' can no be found` during initial machine bootstrap, or if cache has been invalidated.

### CODE REVIEW

**Comment by drybjed** [comment]
This can be applied to any role, at any time. Does that mean that each role needs to refresh APT cache each time it is run? During the initial run, `debops.apt` is used to configure the APT sources and update the package cache, that should be enough. If you don't use that role in the main playbook, you should at least provide an equivalent.

Otherwise, Debian has `/etc/cron.daily/apt` script which [gets the current cache information each day](https://sources.debian.net/src/apt/1.0.9.8.3/debian/apt.cron.daily/#L439), so that should be sufficient for periodic APT cache update.

**Comment by antoineco** [comment]
I indeed just faced a situation where a host was bootstraped without `debops.apt`, but where `debops.auth` is used to setup the auth layer and users.

If the role is not supposed to work without pre-populating the APT cache I would add a line about it in the docs then.

**Comment by drybjed** [comment]
The `debops.auth` role is part of the `common` DebOps playbook and was designed from the start with this in mind, that the APT cache and source configuration is done by a different role, ie. `debops.apt`. In fact most of the DebOps roles are written with the idea that the roles in the `common` playbook are applied and their configuration is in effect.

If you want to bootstrap the host with `debops.auth` role directly, without using the `common` playbook which in essence is one giant bootstrapping, I would suggest to either make sure that your host deployment infrastructure (ie. a preseed script, LXC template, cloud-init, etc.) updates the APT cache on host boot, since it's a common issue with image-based deployments, or you add a `pre_task` to your first playook to update the APT cache. That should make sure that the package cache is current.

BTW, I plan to move parts of this role to separate roles and switch the used services like `libpam-cracklib` and `nslcd` to different ones, like `libpam-pwquality` and `sssd`. Do you think that you would want to stay with the current ones? They could be moved to separate roles and provided as an alternative in this case.

**Comment by antoineco** [comment]
Granularity is always a good thing in the context of a framework like DebOps, it allows people to fine-tune their config files if they need to. I'm personally fine with the way `libpam-cracklib` is setup currently, defaults seem very sane and I don't use `nslcd` at all, so I can't really tell if a separate role is needed or not. 

Anyway, thank you for the clarification, I've added `debops.apt` right after `debops.core` in my custom playbook and it populates the cache as expected 👍  It's not such an overhead, so I'm closing this.

**Pull request closed without merging**
